Updated base.

diff --git a/base/reth/Dockerfile b/base/reth/Dockerfile
--- a/base/reth/Dockerfile
+++ b/base/reth/Dockerfile
@@ -1,34 +1,47 @@
-FROM golang:1.22 AS op
+FROM golang:1.23 AS op
 
-WORKDIR /app
-
-ENV REPO=https://github.com/ethereum-optimism/optimism.git
-ENV VERSION=v1.13.2
-ENV COMMIT=c8b9f62736a7dad7e569719a84c406605f4472e6
-RUN git clone $REPO --branch op-node/$VERSION --single-branch . && \
-    git switch -c branch-$VERSION && \
-    bash -c '[ "$(git rev-parse HEAD)" = "$COMMIT" ]'
-
-# Install 'just'
 RUN curl -sSfL 'https://just.systems/install.sh' | bash -s -- --to /usr/local/bin
 
-RUN cd op-node && \
-    make VERSION=$VERSION op-node
+WORKDIR /app
 
-FROM rust:1.85 AS reth
+COPY versions.env /tmp/versions.env
+
+RUN . /tmp/versions.env && git clone $OP_NODE_REPO --branch $OP_NODE_TAG --single-branch . && \
+    git switch -c branch-$OP_NODE_TAG && \
+    bash -c '[ "$(git rev-parse HEAD)" = "$OP_NODE_COMMIT" ]'
+
+RUN . /tmp/versions.env && cd op-node && \
+    make VERSION=$OP_NODE_TAG op-node
+
+FROM rust:1.87 AS reth
 
 WORKDIR /app
+
+COPY versions.env /tmp/versions.env
 
 RUN apt-get update && apt-get -y upgrade && apt-get install -y git libclang-dev pkg-config curl build-essential
 
-ENV REPO=https://github.com/paradigmxyz/reth.git
-ENV VERSION=v1.3.12
-ENV COMMIT=6f8e7258f4733279080e4bd8345ce50538a40d6e
-RUN git clone $REPO --branch $VERSION --single-branch . && \
-    git switch -c branch-$VERSION && \
-    bash -c '[ "$(git rev-parse HEAD)" = "$COMMIT" ]'
+RUN . /tmp/versions.env && git clone $OP_RETH_REPO --branch $OP_RETH_TAG --single-branch . && \
+    git switch -c branch-$OP_RETH_TAG && \
+    bash -c '[ "$(git rev-parse HEAD)" = "$OP_RETH_COMMIT" ]'
 
 RUN cargo build --bin op-reth --profile maxperf --manifest-path crates/optimism/bin/Cargo.toml
+
+FROM rust:1.87 AS reth-base
+
+WORKDIR /app
+
+COPY versions.env /tmp/versions.env
+
+RUN apt-get update && apt-get -y upgrade && \
+    apt-get install -y git libclang-dev pkg-config curl build-essential && \
+    rm -rf /var/lib/apt/lists/*
+
+RUN . /tmp/versions.env && git clone $BASE_RETH_NODE_REPO . && \
+    git checkout tags/$BASE_RETH_NODE_TAG && \
+    bash -c '[ "$(git rev-parse HEAD)" = "$BASE_RETH_NODE_COMMIT" ]' || (echo "Commit hash verification failed" && exit 1)
+
+RUN cargo build --bin base-reth-node --release
 
 FROM ubuntu:22.04
 
@@ -41,6 +54,7 @@ WORKDIR /app
 
 COPY --from=op /app/op-node/bin/op-node ./
 COPY --from=reth /app/target/maxperf/op-reth ./
+COPY --from=reth-base /app/target/release/base-reth-node ./
 COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
 COPY ./reth/reth-entrypoint ./execution-entrypoint
 COPY op-node-entrypoint .
