Project/environment name-based node installation.
With this update it is possible to install on the same server multiple
instances of the same (e.g. full/archive) each one with their own
environment file (that defines the project name).

diff --git a/install b/install
--- a/install
+++ b/install
@@ -45,76 +45,76 @@ reverseproxy-check() {
 }
 
 node-start() {
-    ENV_FILE="${2:-$1}.env"
+    PROJECT_NAME="${2:-$1}"
 
     [ -f "$NODEDIR/$1/$1.yml" ] || { echo "Error: $1.yml file not found."; return 1; }
-    [ -f "$NODEDIR/$1/${ENV_FILE}" ] || { echo "Error: ${ENV_FILE} file not found"; return 1; }
-    source $NODEDIR/$1/${ENV_FILE}
+    [ -f "$NODEDIR/$1/${PROJECT_NAME}.env" ] || { echo "Error: ${PROJECT_NAME}.env file not found"; return 1; }
+    source $NODEDIR/$1/${PROJECT_NAME}.env
 
     case $1 in
         "mainnet")
-            [ -z $CONFIG_PATH ] && ! volume-exists mainnet_config && docker volume create mainnet_config
+            [ -z $CONFIG_PATH ] && ! volume-exists ${PROJECT_NAME}_config && docker volume create ${PROJECT_NAME}_config
             if [ "${ERIGON_TAG:0:2}" = "v2" ]; then
-                cp $NODEDIR/mainnet/config-v2.yaml ${CONFIG_PATH:-/var/lib/docker/volumes/mainnet_config/_data}/config.yaml
+                cp $NODEDIR/mainnet/config-v2.yaml ${CONFIG_PATH:-/var/lib/docker/volumes/${PROJECT_NAME}_config/_data}/config.yaml
             else
-                cp $NODEDIR/mainnet/config.yaml ${CONFIG_PATH:-/var/lib/docker/volumes/mainnet_config/_data}/config.yaml
+                cp $NODEDIR/mainnet/config.yaml ${CONFIG_PATH:-/var/lib/docker/volumes/${PROJECT_NAME}_config/_data}/config.yaml
             fi
 
-            [ -z $DATABASE_PATH ] && ! volume-exists mainnet_data && docker volume create mainnet_data
+            [ -z $DATABASE_PATH ] && ! volume-exists ${PROJECT_NAME}_data && docker volume create ${PROJECT_NAME}_data
             ;;
         "gnosis")
-            [ -z $CONFIG_PATH ] && ! volume-exists gnosis_config && docker volume create gnosis_config
+            [ -z $CONFIG_PATH ] && ! volume-exists ${PROJECT_NAME}_config && docker volume create ${PROJECT_NAME}_config
             if [ "${ERIGON_TAG:0:2}" = "v2" ]; then
-                cp $NODEDIR/gnosis/config-v2.yaml ${CONFIG_PATH:-/var/lib/docker/volumes/gnosis_config/_data}/config.yaml
+                cp $NODEDIR/gnosis/config-v2.yaml ${CONFIG_PATH:-/var/lib/docker/volumes/${PROJECT_NAME}_config/_data}/config.yaml
             else
-                cp $NODEDIR/gnosis/config.yaml ${CONFIG_PATH:-/var/lib/docker/volumes/gnosis_config/_data}/config.yaml
+                cp $NODEDIR/gnosis/config.yaml ${CONFIG_PATH:-/var/lib/docker/volumes/${PROJECT_NAME}_config/_data}/config.yaml
             fi
 
-            [ -z $DATABASE_PATH ] && ! volume-exists gnosis_data && docker volume create gnosis_data
+            [ -z $DATABASE_PATH ] && ! volume-exists ${PROJECT_NAME}_data && docker volume create ${PROJECT_NAME}_data
             ;;
         "matic")
-            [ -z $CONFIG_PATH ] && ! volume-exists matic_config && docker volume create matic_config
+            [ -z $CONFIG_PATH ] && ! volume-exists ${PROJECT_NAME}_config && docker volume create ${PROJECT_NAME}_config
             if [ "${ERIGON_TAG:0:2}" = "v2" ]; then
-                cp $NODEDIR/matic/config-v2.yaml ${CONFIG_PATH:-/var/lib/docker/volumes/matic_config/_data}/config.yaml
+                cp $NODEDIR/matic/config-v2.yaml ${CONFIG_PATH:-/var/lib/docker/volumes/${PROJECT_NAME}_config/_data}/config.yaml
             else
-                cp $NODEDIR/matic/config.yaml ${CONFIG_PATH:-/var/lib/docker/volumes/matic_config/_data}/config.yaml
+                cp $NODEDIR/matic/config.yaml ${CONFIG_PATH:-/var/lib/docker/volumes/${PROJECT_NAME}_config/_data}/config.yaml
             fi
 
-            [ -z $DATABASE_PATH ] && ! volume-exists matic_data && docker volume create matic_data
+            [ -z $DATABASE_PATH ] && ! volume-exists ${PROJECT_NAME}_data && docker volume create ${PROJECT_NAME}_data
             ;;
         "arbitrum-one")
-            [ -z $CLASSIC_DATABASE_PATH ] && ! volume-exists arbitrum-one_classic-data && docker volume create arbitrum-one_classic-data
-            # curl https://snapshot.arbitrum.foundation/arb1/classic-archive.tar | tar -xv -C  ${CLASSIC_DATABASE_PATH:-"/var/lib/docker/volumes/arbitrum-one_classic-data/_data/"}
+            [ -z $CLASSIC_DATABASE_PATH ] && ! volume-exists ${PROJECT_NAME}_classic-data && docker volume create ${PROJECT_NAME}_classic-data
+            # curl https://snapshot.arbitrum.foundation/arb1/classic-archive.tar | tar -xv -C  ${CLASSIC_DATABASE_PATH:-"/var/lib/docker/volumes/${PROJECT_NAME}_classic-data/_data/"}
 
-            [ -z $NITRO_DATABASE_PATH ] && ! volume-exists arbitrum-one_nitro-data && docker volume create arbitrum-one_nitro-data
+            [ -z $NITRO_DATABASE_PATH ] && ! volume-exists ${PROJECT_NAME}_nitro-data && docker volume create ${PROJECT_NAME}_nitro-data
             ;;
         "avalanche")
-            [ -z $CONFIG_PATH ] && ! volume-exists avalanche_config && docker volume create avalanche_config
-            cp $NODE_DIR/avalanche/node.json ${CONFIG_PATH:-/var/lib/docker/volumes/avalanche_config/_data/}
+            [ -z $CONFIG_PATH ] && ! volume-exists ${PROJECT_NAME}_config && docker volume create ${PROJECT_NAME}_config
+            cp $NODE_DIR/avalanche/node.json ${CONFIG_PATH:-/var/lib/docker/volumes/${PROJECT_NAME}_config/_data/}
 
-            [ -z $CCONFIG_PATH ] && ! volume-exists avalanche_c-config && docker volume create avalanche_c-config
-            cp $NODE_DIR/avalanche/config.json ${CCONFIG_PATH:-/var/lib/docker/volumes/avalanche_c-config/_data/}
+            [ -z $CCONFIG_PATH ] && ! volume-exists ${PROJECT_NAME}_c-config && docker volume create ${PROJECT_NAME}_c-config
+            cp $NODE_DIR/avalanche/config.json ${CCONFIG_PATH:-/var/lib/docker/volumes/${PROJECT_NAME}_c-config/_data/}
 
-            [ -z $DATABASE_PATH ] && ! volume-exists avalanche_data && docker volume create avalanche_data
+            [ -z $DATABASE_PATH ] && ! volume-exists ${PROJECT_NAME}_data && docker volume create ${PROJECT_NAME}_data
             ;;
         "optimism")
-            [ -z $SCRIPTS_PATH ] && ! volume-exists optimism_scripts && docker volume create optimism_scripts
-            cp $NODE_DIR/optimism/scripts/* ${SCRIPTS_PATH:-/var/lib/docker/volumes/optimism_scripts/_data/}
+            [ -z $SCRIPTS_PATH ] && ! volume-exists ${PROJECT_NAME}_scripts && docker volume create ${PROJECT_NAME}_scripts
+            cp $NODE_DIR/optimism/scripts/* ${SCRIPTS_PATH:-/var/lib/docker/volumes/${PROJECT_NAME}_scripts/_data/}
 
-            [ -z $CONFIG_PATH ] && ! volume-exists optimism_config && docker volume create optimism_config
-            [ -z $SHARED_PATH ] && ! volume-exists optimism_shared && docker volume create optimism_shared
-            [ -z $DOWNLOADS_PATH ] && ! volume-exists optimism_downloads && docker volume create optimism_downloads
-            [ -z $INFLUXDB_PATH ] && ! volume-exists optimism_influxdb && docker volume create optimism_influxdb
-            [ -z $OPGETH_DATABASE_PATH ] && ! volume-exists optimism_opgeth && docker volume create optimism_opgeth
-            [ -z $L2GETH_DATABASE_PATH ] && ! volume-exists optimism_l2geth && docker volume create optimism_l2geth
+            [ -z $CONFIG_PATH ] && ! volume-exists ${PROJECT_NAME}_config && docker volume create ${PROJECT_NAME}_config
+            [ -z $SHARED_PATH ] && ! volume-exists ${PROJECT_NAME}_shared && docker volume create ${PROJECT_NAME}_shared
+            [ -z $DOWNLOADS_PATH ] && ! volume-exists ${PROJECT_NAME}_downloads && docker volume create ${PROJECT_NAME}_downloads
+            [ -z $INFLUXDB_PATH ] && ! volume-exists ${PROJECT_NAME}_influxdb && docker volume create ${PROJECT_NAME}_influxdb
+            [ -z $OPGETH_DATABASE_PATH ] && ! volume-exists ${PROJECT_NAME}_opgeth && docker volume create ${PROJECT_NAME}_opgeth
+            [ -z $L2GETH_DATABASE_PATH ] && ! volume-exists ${PROJECT_NAME}_l2geth && docker volume create ${PROJECT_NAME}_l2geth
             ;;
         "celo")
             # apt install libusb-1.0-0-dev libudev-dev
             # npm install -g @celo/celocli
-            [ -z $DATABASE_PATH ] && ! volume-exists celo_data && docker volume create celo_data
+            [ -z $DATABASE_PATH ] && ! volume-exists ${PROJECT_NAME}_data && docker volume create ${PROJECT_NAME}_data
             ;;
         "base")
-            [ -z $DATABASE_PATH ] && ! volume-exists base_data && docker volume create base_data
+            [ -z $DATABASE_PATH ] && ! volume-exists ${PROJECT_NAME}_data && docker volume create ${PROJECT_NAME}_data
             # tar --use-compress-program=unzstd -xvf archive.tar.zst
             # SNAP_LATEST=$(curl https://mainnet-archive-snapshots.base.org/latest)
             # cd ${DATABASE_PATH:-"/var/lib/docker/volumes/base_data/_data/"} && \
@@ -123,10 +123,10 @@ node-start() {
             # rm -rf $SNAP_LATEST
             ;;
         "linea")
-            [ -z $DATABASE_PATH ] && ! volume-exists linea_data && docker volume create linea_data
+            [ -z $DATABASE_PATH ] && ! volume-exists ${PROJECT_NAME}_data && docker volume create ${PROJECT_NAME}_data
             ;;
         "scroll")
-            [ -z $DATABASE_PATH ] && ! volume-exists scroll_data && docker volume create scroll_data
+            [ -z $DATABASE_PATH ] && ! volume-exists ${PROJECT_NAME}_data && docker volume create ${PROJECT_NAME}_data
             ;;
         *)
             echo "Chain not supported yet!"
@@ -134,37 +134,37 @@ node-start() {
             ;;
     esac
 
-    COMPOSE_PROJECT_NAME=$1 \
+    COMPOSE_PROJECT_NAME=${PROJECT_NAME} \
     COMPOSE_FILE=$NODE_DIR/$1/$1.yml \
-    docker compose --env-file $NODEDIR/$1/${ENV_FILE} pull
+    docker compose --env-file $NODEDIR/$1/${PROJECT_NAME}.env pull
 
-    COMPOSE_PROJECT_NAME=$1 \
+    COMPOSE_PROJECT_NAME=${PROJECT_NAME} \
     COMPOSE_FILE=$NODE_DIR/$1/$1.yml \
-    docker compose --env-file $NODEDIR/$1/${ENV_FILE} up -d --remove-orphans --build
+    docker compose --env-file $NODEDIR/$1/${PROJECT_NAME}.env up -d --remove-orphans --build
 
     if [ ! -z $MAINNET_LOCAL_NETWORK ]; then
         case $1 in
             "arbitrum-one")
-                nets=$(docker container inspect --format '{{range $net,$v := .NetworkSettings.Networks}}{{printf "%s\n" $net}}{{end}}' arbitrum-one-nitro)
-                [[ ! ${nets[@]} =~ "$MAINNET_LOCAL_NETWORK" ]] && docker network connect $MAINNET_LOCAL_NETWORK arbitrum-one-nitro
-                nets=$(docker container inspect --format '{{range $net,$v := .NetworkSettings.Networks}}{{printf "%s\n" $net}}{{end}}' arbitrum-one-classic)
-                [[ ! ${nets[@]} =~ "$MAINNET_LOCAL_NETWORK" ]] && docker network connect $MAINNET_LOCAL_NETWORK arbitrum-one-classic
+                nets=$(docker container inspect --format '{{range $net,$v := .NetworkSettings.Networks}}{{printf "%s\n" $net}}{{end}}' ${PROJECT_NAME}-nitro)
+                [[ ! ${nets[@]} =~ "$MAINNET_LOCAL_NETWORK" ]] && docker network connect $MAINNET_LOCAL_NETWORK ${PROJECT_NAME}-nitro
+                nets=$(docker container inspect --format '{{range $net,$v := .NetworkSettings.Networks}}{{printf "%s\n" $net}}{{end}}' ${PROJECT_NAME}-classic)
+                [[ ! ${nets[@]} =~ "$MAINNET_LOCAL_NETWORK" ]] && docker network connect $MAINNET_LOCAL_NETWORK ${PROJECT_NAME}-classic
             ;;
             "optimism")
-                nets=$(docker container inspect --format '{{range $net,$v := .NetworkSettings.Networks}}{{printf "%s\n" $net}}{{end}}' optimism-op-node)
-                [[ ! ${nets[@]} =~ "$MAINNET_LOCAL_NETWORK" ]] && docker network connect $MAINNET_LOCAL_NETWORK optimism-op-node
-                nets=$(docker container inspect --format '{{range $net,$v := .NetworkSettings.Networks}}{{printf "%s\n" $net}}{{end}}' optimism-l2geth)
-                [[ ! ${nets[@]} =~ "$MAINNET_LOCAL_NETWORK" ]] && docker network connect $MAINNET_LOCAL_NETWORK optimism-l2geth
+                nets=$(docker container inspect --format '{{range $net,$v := .NetworkSettings.Networks}}{{printf "%s\n" $net}}{{end}}' ${PROJECT_NAME}-op-node)
+                [[ ! ${nets[@]} =~ "$MAINNET_LOCAL_NETWORK" ]] && docker network connect $MAINNET_LOCAL_NETWORK ${PROJECT_NAME}-op-node
+                nets=$(docker container inspect --format '{{range $net,$v := .NetworkSettings.Networks}}{{printf "%s\n" $net}}{{end}}' ${PROJECT_NAME}-l2geth)
+                [[ ! ${nets[@]} =~ "$MAINNET_LOCAL_NETWORK" ]] && docker network connect $MAINNET_LOCAL_NETWORK ${PROJECT_NAME}-l2geth
             ;;
             "base")
-                nets=$(docker container inspect --format '{{range $net,$v := .NetworkSettings.Networks}}{{printf "%s\n" $net}}{{end}}' base-execution)
-                [[ ! ${nets[@]} =~ "$MAINNET_LOCAL_NETWORK" ]] && docker network connect $MAINNET_LOCAL_NETWORK base-execution
-                nets=$(docker container inspect --format '{{range $net,$v := .NetworkSettings.Networks}}{{printf "%s\n" $net}}{{end}}' base-node)
-                [[ ! ${nets[@]} =~ "$MAINNET_LOCAL_NETWORK" ]] && docker network connect $MAINNET_LOCAL_NETWORK base-node
+                nets=$(docker container inspect --format '{{range $net,$v := .NetworkSettings.Networks}}{{printf "%s\n" $net}}{{end}}' ${PROJECT_NAME}-execution)
+                [[ ! ${nets[@]} =~ "$MAINNET_LOCAL_NETWORK" ]] && docker network connect $MAINNET_LOCAL_NETWORK ${PROJECT_NAME}-execution
+                nets=$(docker container inspect --format '{{range $net,$v := .NetworkSettings.Networks}}{{printf "%s\n" $net}}{{end}}' ${PROJECT_NAME}-node)
+                [[ ! ${nets[@]} =~ "$MAINNET_LOCAL_NETWORK" ]] && docker network connect $MAINNET_LOCAL_NETWORK ${PROJECT_NAME}-node
             ;;
-            "scroll")
-                nets=$(docker container inspect --format '{{range $net,$v := .NetworkSettings.Networks}}{{printf "%s\n" $net}}{{end}}' scroll)
-                [[ ! ${nets[@]} =~ "$MAINNET_LOCAL_NETWORK" ]] && docker network connect $MAINNET_LOCAL_NETWORK scroll
+            *)
+                nets=$(docker container inspect --format '{{range $net,$v := .NetworkSettings.Networks}}{{printf "%s\n" $net}}{{end}}' ${PROJECT_NAME})
+                [[ ! ${nets[@]} =~ "$MAINNET_LOCAL_NETWORK" ]] && docker network connect $MAINNET_LOCAL_NETWORK ${PROJECT_NAME}
             ;;
         esac 
     fi
@@ -174,16 +174,16 @@ node-start() {
 
         case $1 in
             "arbitrum-one")
-                container=$1-nitro
+                container=${PROJECT_NAME}-nitro
             ;;
             "optimism")
-                container=$1-op-geth
+                container=${PROJECT_NAME}-op-geth
             ;;
             "base")
-                container=$1-execution
+                container=${PROJECT_NAME}-execution
             ;;
             *)
-                container=$1
+                container=${PROJECT_NAME}
             ;;
         esac
 
@@ -193,13 +193,13 @@ node-start() {
         fi
 
         VHOST_PATH=/var/lib/docker/volumes/reverse-proxy_vhost/_data
-        [ -f "${VHOST_PATH}/${SUBDOMAIN:-$1}.${HOST}" ] && rm ${VHOST_PATH}/${SUBDOMAIN:-$1}.${HOST}
+        [ -f "${VHOST_PATH}/${SUBDOMAIN:-${PROJECT_NAME}}.${HOST}" ] && rm ${VHOST_PATH}/${SUBDOMAIN:-${PROJECT_NAME}}.${HOST}
 
         if [ ! -z $WHITELIST ]; then
             for (( j=0; j<${#WHITELIST[@]}; j++ )); do
-                echo "allow ${WHITELIST[$j]};" >> ${VHOST_PATH}/${SUBDOMAIN:-$1}.${HOST}
+                echo "allow ${WHITELIST[$j]};" >> ${VHOST_PATH}/${SUBDOMAIN:-${PROJECT_NAME}}.${HOST}
             done
-            echo "deny all;" >> ${VHOST_PATH}/${SUBDOMAIN:-$1}.${HOST}
+            echo "deny all;" >> ${VHOST_PATH}/${SUBDOMAIN:-${PROJECT_NAME}}.${HOST}
         fi
     fi
     # unset HOST SUBDOMAIN WHITELIST DATABASE_PATH MAINNET_LOCAL_NETWORK
@@ -210,6 +210,7 @@ node-install() {
         "mainnet" "Ethereum Mainnet" OFF \
         "arbitrum-one" "Arbitrum-One Nitro & Classic" OFF \
         "matic" "Polygon Matic" OFF \
+        "gnosis" "Gnosis" OFF \
         "optimism" "Optimism" OFF \
         "avalanche" "Avalanche" OFF \
         "celo" "Celo" OFF \
@@ -222,7 +223,7 @@ node-install() {
         { echo "No option selected"; return; }
     else
         for CHAIN in $CHAINS; do
-            ENVFILE=$(whiptail --title "Blockchain Node Setup" --inputbox "Environment file $CHAIN" 8 78 "$CHAIN" 3>&1 1>&2 2>&3) || return
+            ENVFILE=$(whiptail --title "Blockchain Node Setup" --inputbox "Project name for $CHAIN (same as environment file)" 8 78 "$CHAIN" 3>&1 1>&2 2>&3) || return
             node-start $CHAIN $ENVFILE
         done
     fi
diff --git a/utils/manage b/utils/manage
--- a/utils/manage
+++ b/utils/manage
@@ -2,12 +2,13 @@
 . $NODE_DIR/install --source
 
 node-stop() {
+    PROJECT_NAME="${2:-$1}"
     [ -f "$NODEDIR/$1/$1.yml" ] || { echo "Error: $1.yml file not found."; return 1; }
-    [ -f "$NODEDIR/$1/$1.env" ] || { echo "Error: $1.env file not found"; return 1; }
+    [ -f "$NODEDIR/$1/${PROJECT_NAME}.env" ] || { echo "Error: ${PROJECT_NAME}.env file not found"; return 1; }
 
-    COMPOSE_PROJECT_NAME=$1 \
+    COMPOSE_PROJECT_NAME=${PROJECT_NAME} \
     COMPOSE_FILE=$NODEDIR/$1/$1.yml \
-    docker compose --env-file $NODEDIR/$1/$1.env stop
+    docker compose --env-file $NODEDIR/$1/${PROJECT_NAME}.env stop
 }
 
 node-restart() {
@@ -15,70 +16,72 @@ node-restart() {
 }
 
 node-monitor() {
-    # Check if session name exists
-    SESSIONEXISTS=$(tmux list-sessions | grep $1)
+    PROJECT_NAME="${2:-$1}"
+
+    SESSIONEXISTS=$(tmux list-sessions | grep ${PROJECT_NAME})
 
     # Set up monitoring interface
     if [ "$SESSIONEXISTS" = "" ]
     then
-        tmux new-session -d -s $1
+        tmux new-session -d -s ${PROJECT_NAME}
         case $1 in
         "mainnet")
             [ -z "$( docker ps | grep ${1} )" ] && { echo "Node ${1} not found."; return; }
-            tmux rename-window -t 0 'mainnet-log' && tmux send-keys -t 'mainnet-log' "docker logs mainnet --tail 10 -f | pino-pretty -c -t" C-m
-            tmux new-window -t $1:1 -n 'mainnet-container' && tmux send-keys -t 'mainnet-container' "docker exec -it mainnet sh" C-m
+            tmux rename-window -t 0 'mainnet-log' && tmux send-keys -t 'mainnet-log' "docker logs ${PROJECT_NAME} --tail 10 -f | pino-pretty -c -t" C-m
+            tmux new-window -t ${PROJECT_NAME}:1 -n 'mainnet-container' && tmux send-keys -t 'mainnet-container' "docker exec -it ${PROJECT_NAME} sh" C-m
         ;;
         "gnosis")
-            tmux rename-window -t 0 'gnosis-log' && tmux send-keys -t 'gnosis-log' "docker logs gnosis --tail 10 -f | pino-pretty -c -t" C-m
-            tmux new-window -t $1:1 -n 'gnosis-container' && tmux send-keys -t 'gnosis-container' "docker exec -it gnosis sh" C-m
+            tmux rename-window -t 0 'gnosis-log' && tmux send-keys -t 'gnosis-log' "docker logs ${PROJECT_NAME} --tail 10 -f | pino-pretty -c -t" C-m
+            tmux new-window -t ${PROJECT_NAME}:1 -n 'gnosis-container' && tmux send-keys -t 'gnosis-container' "docker exec -it ${PROJECT_NAME} sh" C-m
         ;;
         "matic")
-            tmux rename-window -t 0 'matic-log' && tmux send-keys -t 'matic-log' "docker logs matic --tail 10 -f | pino-pretty -c -t" C-m
-            tmux new-window -t $1:1 -n 'matic-container' && tmux send-keys -t 'matic-container' "docker exec -it matic sh" C-m
+            tmux rename-window -t 0 'matic-log' && tmux send-keys -t 'matic-log' "docker logs ${PROJECT_NAME} --tail 10 -f | pino-pretty -c -t" C-m
+            tmux new-window -t ${PROJECT_NAME}:1 -n 'matic-container' && tmux send-keys -t 'matic-container' "docker exec -it ${PROJECT_NAME} sh" C-m
         ;;
         "arbitrum-one")    
-            tmux rename-window -t 0 'nitro-log' && tmux send-keys -t 'nitro-log' "docker logs ${1}-nitro --tail 10 -f | pino-pretty -c -t" C-m
-            tmux new-window -t $1:1 -n 'classic-log' && tmux send-keys -t 'classic-log' "docker logs ${1}-classic --tail 10 -f | pino-pretty -c -t" C-m
-            tmux new-window -t $1:2 -n 'nitro-cli' && tmux send-keys -t 'nitro-cli' "docker exec -it ${1}-nitro /bin/bash" C-m
-            tmux new-window -t $1:3 -n 'classic-cli' && tmux send-keys -t 'classic-cli' "docker exec -it ${1}-classic /bin/bash" C-m
+            tmux rename-window -t 0 'nitro-log' && tmux send-keys -t 'nitro-log' "docker logs ${PROJECT_NAME}-nitro --tail 10 -f | pino-pretty -c -t" C-m
+            tmux new-window -t ${PROJECT_NAME}:1 -n 'classic-log' && tmux send-keys -t 'classic-log' "docker logs ${PROJECT_NAME}-classic --tail 10 -f | pino-pretty -c -t" C-m
+            tmux new-window -t ${PROJECT_NAME}:2 -n 'nitro-cli' && tmux send-keys -t 'nitro-cli' "docker exec -it ${PROJECT_NAME}-nitro /bin/bash" C-m
+            tmux new-window -t ${PROJECT_NAME}:3 -n 'classic-cli' && tmux send-keys -t 'classic-cli' "docker exec -it ${PROJECT_NAME}-classic /bin/bash" C-m
         ;;
         "avalanche")
-            tmux rename-window -t 0 'avalanche-log' && tmux send-keys -t 'avalanche-log' "docker logs ${1} --tail 10 -f | pino-pretty -c -t" C-m
-            tmux new-window -t $1:1 -n 'avalanche-cli' && tmux send-keys -t 'avalanche-cli' "docker exec -it ${1} /bin/bash" C-m
+            tmux rename-window -t 0 'avalanche-log' && tmux send-keys -t 'avalanche-log' "docker logs ${PROJECT_NAME} --tail 10 -f | pino-pretty -c -t" C-m
+            tmux new-window -t ${PROJECT_NAME}:1 -n 'avalanche-cli' && tmux send-keys -t 'avalanche-cli' "docker exec -it ${PROJECT_NAME} /bin/bash" C-m
         ;;
         "optimism")
-            tmux rename-window -t 0 'op-geth' && tmux send-keys -t 'op-geth' "docker logs ${1}-op-geth --tail 10 -f | pino-pretty -c -t" C-m
-            tmux new-window -t $1:1 -n 'op-node' && tmux send-keys -t 'op-node' "docker logs ${1}-op-node --tail 10 -f | pino-pretty -c -t" C-m
-            tmux new-window -t $1:2 -n 'bedrock-init' && tmux send-keys -t 'bedrock-init' "docker logs ${1}-bedrock-init --tail 10 -f | pino-pretty -c -t" C-m
-            tmux new-window -t $1:3 -n 'l2geth' && tmux send-keys -t 'l2geth' "docker logs ${1}-l2geth --tail 10 -f | pino-pretty -c -t" C-m
+            tmux rename-window -t 0 'op-geth' && tmux send-keys -t 'op-geth' "docker logs ${PROJECT_NAME}-op-geth --tail 10 -f | pino-pretty -c -t" C-m
+            tmux new-window -t ${PROJECT_NAME}:1 -n 'op-node' && tmux send-keys -t 'op-node' "docker logs ${PROJECT_NAME}-op-node --tail 10 -f | pino-pretty -c -t" C-m
+            tmux new-window -t ${PROJECT_NAME}:2 -n 'bedrock-init' && tmux send-keys -t 'bedrock-init' "docker logs ${PROJECT_NAME}-bedrock-init --tail 10 -f | pino-pretty -c -t" C-m
+            tmux new-window -t ${PROJECT_NAME}:3 -n 'l2geth' && tmux send-keys -t 'l2geth' "docker logs ${PROJECT_NAME}-l2geth --tail 10 -f | pino-pretty -c -t" C-m
         ;;
         "celo")
-            tmux rename-window -t 0 'celo-log' && tmux send-keys -t 'celo-log' "docker logs celo --tail 10 -f | pino-pretty -c -t" C-m
-            tmux new-window -t $1:1 -n 'celo-cli' && tmux send-keys -t 'celo-cli' "docker exec -it celo /bin/bash" C-m
+            tmux rename-window -t 0 'celo-log' && tmux send-keys -t 'celo-log' "docker logs ${PROJECT_NAME} --tail 10 -f | pino-pretty -c -t" C-m
+            tmux new-window -t ${PROJECT_NAME}:1 -n 'celo-cli' && tmux send-keys -t 'celo-cli' "docker exec -it ${PROJECT_NAME} /bin/bash" C-m
         ;;
         "linea")
-            tmux rename-window -t 0 'linea-log' && tmux send-keys -t 'linea-log' "docker logs linea --tail 10 -f | pino-pretty -c -t" C-m
-            tmux new-window -t $1:1 -n 'linea-cli' && tmux send-keys -t 'linea-cli' "docker exec -it linea sh" C-m
+            tmux rename-window -t 0 'linea-log' && tmux send-keys -t 'linea-log' "docker logs ${PROJECT_NAME} --tail 10 -f | pino-pretty -c -t" C-m
+            tmux new-window -t ${PROJECT_NAME}:1 -n 'linea-cli' && tmux send-keys -t 'linea-cli' "docker exec -it ${PROJECT_NAME} sh" C-m
         ;;
         "base")
-            tmux rename-window -t 0 'base-execution-log' && tmux send-keys -t 'base-execution-log' "docker logs base-execution --tail 10 -f | pino-pretty -c -t" C-m
-            tmux new-window -t $1:1 -n 'base-node-log' && tmux send-keys -t 'base-node-log' "docker logs base-node --tail 10 -f | pino-pretty -c -t" C-m
-            tmux new-window -t $1:2 -n 'base-execution-cli' && tmux send-keys -t 'base-execution-cli' "docker exec -it base-execution /bin/bash" C-m
-            tmux new-window -t $1:3 -n 'base-node-cli' && tmux send-keys -t 'base-node-cli' "docker exec -it base-node /bin/bash" C-m
+            tmux rename-window -t 0 'base-execution-log' && tmux send-keys -t 'base-execution-log' "docker logs ${PROJECT_NAME}-execution --tail 10 -f | pino-pretty -c -t" C-m
+            tmux new-window -t ${PROJECT_NAME}:1 -n 'base-node-log' && tmux send-keys -t 'base-node-log' "docker logs ${PROJECT_NAME}-node --tail 10 -f | pino-pretty -c -t" C-m
+            tmux new-window -t ${PROJECT_NAME}:2 -n 'base-execution-cli' && tmux send-keys -t 'base-execution-cli' "docker exec -it ${PROJECT_NAME}-execution /bin/bash" C-m
+            tmux new-window -t ${PROJECT_NAME}:3 -n 'base-node-cli' && tmux send-keys -t 'base-node-cli' "docker exec -it ${PROJECT_NAME}-node /bin/bash" C-m
         ;;
         "fantom")
-            tmux rename-window -t 0 'fantom-cli' && tmux send-keys -t 'fantom-cli' "docker exec -it fantom /bin/bash" C-m
-            tmux new-window -t $1:1 -n 'fantom-log' && tmux send-keys -t 'fantom-log' "docker logs fantom --tail 10 -f | pino-pretty -c -t" C-m
+            tmux rename-window -t 0 'fantom-cli' && tmux send-keys -t 'fantom-cli' "docker exec -it ${PROJECT_NAME} /bin/bash" C-m
+            tmux new-window -t ${PROJECT_NAME}:1 -n 'fantom-log' && tmux send-keys -t 'fantom-log' "docker logs ${PROJECT_NAME} --tail 10 -f | pino-pretty -c -t" C-m
         ;;
         "scroll")
-            tmux rename-window -t 0 'scroll-log' && tmux send-keys -t 'scroll-log' "docker logs scroll --tail 10 -f | pino-pretty -c -t" C-m
-            tmux new-window -t $1:1 -n 'scroll-cli' && tmux send-keys -t 'scroll-cli' "docker exec -it scroll sh" C-m
+            tmux rename-window -t 0 'scroll-log' && tmux send-keys -t 'scroll-log' "docker logs ${PROJECT_NAME} --tail 10 -f | pino-pretty -c -t" C-m
+            tmux new-window -t ${PROJECT_NAME}:1 -n 'scroll-cli' && tmux send-keys -t 'scroll-cli' "docker exec -it ${PROJECT_NAME} sh" C-m
         ;;
         *)
+            tmux kill-session -t ${PROJECT_NAME}
             echo "Chain not supported!"
             return
         ;;
         esac
     fi
-    tmux attach-session -t $1:0
+    tmux attach-session -t ${PROJECT_NAME}:0
 }
