Fixed various bugs.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -50,10 +50,10 @@ node-install() {
         "optimism" "Optimism" OFF \
         "avalanche" "Avalanche" OFF \
         "celo" "Celo" OFF \
-        "fantom" "Fantom" OFF 3>&1 1>&2 2>&3) || { echo "User exit"; exit -1; }
+        "fantom" "Fantom" OFF 3>&1 1>&2 2>&3) || { echo "User exit"; return; }
 
     if [ -z "$CHOICES" ]; then
-        echo "No option selected"
+        { echo "No option selected"; return; }
     else
         for CHOICE in $CHOICES; do
             case "$CHOICE" in
@@ -103,7 +103,7 @@ node-install() {
                 ;;
             *)
                 echo "$CHOICE not available yet" >&2
-                exit 1
+                return
                 ;;
             esac
 
@@ -121,7 +121,7 @@ node-install() {
             if [ ! -z "$HOST" ]; then
                 reverseproxy-check || { echo "Error: reverse proxy not running"; return 1; }
 
-                case $1 in
+                case $CHOICE in
                     "arbitrum-one")
                         docker network connect reverse-proxy arbitrum-one-nitro 
                     ;;
@@ -129,20 +129,20 @@ node-install() {
                         docker network connect reverse-proxy optimism-op-geth
                     ;;
                     *)
-                        docker network connect reverse-proxy $1
+                        docker network connect reverse-proxy $CHOICE
                     ;;
                 esac
 
                 if [ ! -z $WHITELIST ]; then
                     VHOST_PATH=/var/lib/docker/volumes/reverse-proxy_vhost/_data
                     for (( j=0; j<${#WHITELIST[@]}; j++ )); do
-                        echo "allow ${WHITELIST[$j]};" >> ${VHOST_PATH}/$1.${HOST}
+                        echo "allow ${WHITELIST[$j]};" >> ${VHOST_PATH}/${SUBDOMAIN:-$CHOICE}.${HOST}
                     done
-                    echo "deny all;" >> ${VHOST_PATH}/$1.${HOST}
+                    echo "deny all;" >> ${VHOST_PATH}/${SUBDOMAIN:-$CHOICE}.${HOST}
                 fi
             fi
 
-            unset HOST DATABASE_PATH WHITELIST
+            unset HOST SUBDOMAIN DATABASE_PATH WHITELIST
         done
     fi
 
@@ -165,3 +165,4 @@ docker-install || { echo "Error: could not install Docker"; exit 1; }
 
 nodejs-install || { echo "Error: could not install Node.js"; exit 1; }
 
+node-install || { echo "Error: could not install blockchains"; exit 1; }
diff --git a/utils/manage b/utils/manage
--- a/utils/manage
+++ b/utils/manage
@@ -2,20 +2,8 @@
 
 node-start() {
     if [ -f "$NODE_DIR/$1/$1.yml" ]; then
-        [ -f "$NODE_DIR/.env.user" ] || { echo "Error: .env.user file not found"; return 1; }
-        source $NODE_DIR/.env.user
-
-        if [ ! -z $HOST ]; then
-            VHOST_PATH=/var/lib/docker/volumes/reverse-proxy_vhost/_data
-            [ -f "${VHOST_PATH}/${1}.${HOST}" ] && rm ${VHOST_PATH}/${1}.${HOST}
-
-            if [ ! -z $WHITELIST ]; then
-                for (( j=0; j<${#WHITELIST[@]}; j++ )); do
-                    echo "allow ${WHITELIST[$j]};" >> ${VHOST_PATH}/${1}.${HOST}
-                done
-                echo "deny all;" >> ${VHOST_PATH}/$1.${HOST}
-            fi
-        fi
+        [ -f "$NODE_DIR/$1/$1.env" ] || { echo "Error: user $1.env file not found"; return 1; }
+        source $NODE_DIR/$1/$1.env
         
         case $1 in
             "mainnet")
@@ -68,8 +56,8 @@ node-start() {
                 ;;
         esac
 
-        COMPOSE_PROJECT_NAME=$1 COMPOSE_FILE=$NODE_DIR/$1/$1.yml docker compose --env-file $NODE_DIR/.env.user pull
-        COMPOSE_PROJECT_NAME=$1 COMPOSE_FILE=$NODE_DIR/$1/$1.yml docker compose --env-file $NODE_DIR/.env.user up -d --remove-orphans --build
+        COMPOSE_PROJECT_NAME=$1 COMPOSE_FILE=$NODE_DIR/$1/$1.yml docker compose --env-file $NODE_DIR/$1/$1.env pull
+        COMPOSE_PROJECT_NAME=$1 COMPOSE_FILE=$NODE_DIR/$1/$1.yml docker compose --env-file $NODE_DIR/$1/$1.env up -d --remove-orphans --build
 
         if [ ! -z "$HOST" ]; then
             case $1 in
@@ -87,6 +75,16 @@ node-start() {
             if [[ ! ${nets[@]} =~ "reverse-proxy" ]]; then
                 docker network connect reverse-proxy $container
             fi
+
+            VHOST_PATH=/var/lib/docker/volumes/reverse-proxy_vhost/_data
+            [ -f "${VHOST_PATH}/${SUBDOMAIN:-$1}.${HOST}" ] && rm ${VHOST_PATH}/${SUBDOMAIN:-$1}.${HOST}
+
+            if [ ! -z $WHITELIST ]; then
+                for (( j=0; j<${#WHITELIST[@]}; j++ )); do
+                    echo "allow ${WHITELIST[$j]};" >> ${VHOST_PATH}/${SUBDOMAIN:-$1}.${HOST}
+                done
+                echo "deny all;" >> ${VHOST_PATH}/${SUBDOMAIN:-$1}.${HOST}
+            fi
         fi
     else
         echo "$1 configuration file not found."
@@ -95,15 +93,14 @@ node-start() {
 
 node-stop() {
     if [ -f "$NODE_DIR/$1/$1.yml" ]; then
-        COMPOSE_PROJECT_NAME=$1 COMPOSE_FILE=$NODE_DIR/$1/$1.yml docker compose --env-file $NODE_DIR/.env.user stop
+        COMPOSE_PROJECT_NAME=$1 COMPOSE_FILE=$NODE_DIR/$1/$1.yml docker compose --env-file $NODE_DIR/$1/$1.env stop
     else
         echo "$1 configuration file not found."
     fi
 }
 
 node-restart() {
-    node-stop $1
-    node-start $1
+    node-stop $1 && node-start $1
 }
 
 node-monitor() {
@@ -116,22 +113,17 @@ node-monitor() {
         tmux new-session -d -s $1
         case $1 in
         "mainnet")
+            [ -z "$( docker ps | grep ${1} )" ] && { echo "Node ${1} not found."; return; }
             tmux rename-window -t 0 'mainnet-log' && tmux send-keys -t 'mainnet-log' "docker logs mainnet --tail 10 -f | pino-pretty -c -t" C-m
             tmux new-window -t $1:1 -n 'mainnet-container' && tmux send-keys -t 'mainnet-container' "docker exec -it mainnet sh" C-m
-            # tmux new-window -t $1:2 -n 'lighthouse-log' && tmux send-keys -t 'lighthouse-log' "docker logs mainnet-lighthouse --tail 10 -f | pino-pretty -c -t" C-m
-            # tmux new-window -t $1:3 -n 'lighthouse-container' && tmux send-keys -t 'lighthouse-container' "docker exec -it mainnet-lighthouse sh" C-m
         ;;
         "gnosis")
             tmux rename-window -t 0 'gnosis-log' && tmux send-keys -t 'gnosis-log' "docker logs gnosis --tail 10 -f | pino-pretty -c -t" C-m
             tmux new-window -t $1:1 -n 'gnosis-container' && tmux send-keys -t 'gnosis-container' "docker exec -it gnosis sh" C-m
-            # tmux new-window -t $1:2 -n 'lighthouse-container' && tmux send-keys -t 'lighthouse-container' "docker exec -it gnosis-lighthouse sh" C-m
-            # tmux new-window -t $1:3 -n 'lighthouse-log' && tmux send-keys -t 'lighthouse-log' "docker logs gnosis-lighthouse --tail 10 -f | pino-pretty -c -t" C-m
         ;;
         "matic")
             tmux rename-window -t 0 'matic-log' && tmux send-keys -t 'matic-log' "docker logs matic --tail 10 -f | pino-pretty -c -t" C-m
             tmux new-window -t $1:1 -n 'matic-container' && tmux send-keys -t 'matic-container' "docker exec -it matic sh" C-m
-            # tmux new-window -t $1:2 -n 'lighthouse-container' && tmux send-keys -t 'lighthouse-container' "docker exec -it matic-lighthouse sh" C-m
-            # tmux new-window -t $1:3 -n 'lighthouse-log' && tmux send-keys -t 'lighthouse-log' "docker logs matic-lighthouse --tail 10 -f | pino-pretty -c -t" C-m
         ;;
         "arbitrum-one")    
             tmux rename-window -t 0 'nitro-log' && tmux send-keys -t 'nitro-log' "docker logs ${1}-nitro --tail 10 -f | pino-pretty -c -t" C-m
