Various fixes and improvements.

diff --git a/utils/manage b/utils/manage
--- a/utils/manage
+++ b/utils/manage
@@ -1,102 +1,106 @@
 #!/bin/bash
 
 node-start() {
-    if [ -f "$NODE_DIR/$1/$1.yml" ]; then
-        [ -f "$NODE_DIR/$1/$1.env" ] || { echo "Error: user $1.env file not found"; return 1; }
-        source $NODE_DIR/$1/$1.env
+    [ -f "$NODE_DIR/$1/$1.yml" ] || { echo "Error: $1.yml file not found."; return 1; }
+    [ -f "$NODE_DIR/$1/$1.env" ] || { echo "Error: $1.env file not found"; return 1; }
+    source $NODE_DIR/$1/$1.env
         
+    case $1 in
+        "mainnet")
+            if [ "$(docker volume ls -f name=mainnet_config | awk '{print $NF}' | grep -E '^'mainnet_config'$')" ]; then
+                rm -rf /var/lib/docker/volumes/mainnet_config/_data/config.yaml
+            else
+                docker volume create mainnet_config
+            fi
+            cp $NODE_DIR/mainnet/config.yaml /var/lib/docker/volumes/mainnet_config/_data/
+            ;;
+        "gnosis")
+            if [ "$(docker volume ls -f name=gnosis_config | awk '{print $NF}' | grep -E '^'gnosis_config'$')" ]; then
+                rm -rf /var/lib/docker/volumes/gnosis_config/_data/config.yaml
+            else
+                docker volume create gnosis_config
+            fi
+            cp $NODE_DIR/gnosis/config.yaml /var/lib/docker/volumes/gnosis_config/_data/
+            ;;
+        "matic")
+            if [ "$(docker volume ls -f name=matic_config | awk '{print $NF}' | grep -E '^'matic_config'$')" ]; then
+                rm -rf /var/lib/docker/volumes/matic_config/_data/config.yaml
+            else
+                docker volume create matic_config
+            fi
+            cp $NODE_DIR/matic/config.yaml /var/lib/docker/volumes/matic_config/_data/
+            ;;
+        "arbitrum-one")
+            ;;
+        "avalanche")
+            if [ "$(docker volume ls -f name=avalanche_config | awk '{print $NF}' | grep -E '^'avalanche_config'$')" ]; then
+                rm -rf /var/lib/docker/volumes/avalanche_config/_data/config.json
+            else
+                docker volume create avalanche_config
+            fi
+            cp $NODE_DIR/avalanche/node.json /var/lib/docker/volumes/avalanche_config/_data/
+
+            if [ "$(docker volume ls -f name=avalanche-c_config | awk '{print $NF}' | grep -E '^'avalanche-c_config'$')" ]; then
+                rm -rf /var/lib/docker/volumes/avalanche-c_config/_data/config.json
+            else
+                docker volume create avalanche-c_config
+            fi
+            cp $NODE_DIR/avalanche/config.json /var/lib/docker/volumes/avalanche-c_config/_data/
+            ;;
+        "optimism")
+            rm -rf /data/optimism/scripts/*
+            cp $NODE_DIR/optimism/scripts/* /data/optimism/scripts/
+            ;;
+        *)
+            echo "Chain not supported yet!"
+            return
+            ;;
+    esac
+
+    COMPOSE_PROJECT_NAME=$1 \
+    COMPOSE_FILE=$NODE_DIR/$1/$1.yml \
+    docker compose --env-file $NODE_DIR/$1/$1.env pull
+
+    COMPOSE_PROJECT_NAME=$1 \
+    COMPOSE_FILE=$NODE_DIR/$1/$1.yml \
+    docker compose --env-file $NODE_DIR/$1/$1.env up -d --remove-orphans --build
+
+    if [ ! -z "$HOST" ]; then
         case $1 in
-            "mainnet")
-                if [ "$(docker volume ls -f name=mainnet_config | awk '{print $NF}' | grep -E '^'mainnet_config'$')" ]; then
-                    rm -rf /var/lib/docker/volumes/mainnet_config/_data/config.yaml
-                else
-                    docker volume create mainnet_config
-                fi
-                cp $NODE_DIR/mainnet/config.yaml /var/lib/docker/volumes/mainnet_config/_data/
-                ;;
-            "gnosis")
-                if [ "$(docker volume ls -f name=gnosis_config | awk '{print $NF}' | grep -E '^'gnosis_config'$')" ]; then
-                    rm -rf /var/lib/docker/volumes/gnosis_config/_data/config.yaml
-                else
-                    docker volume create gnosis_config
-                fi
-                cp $NODE_DIR/gnosis/config.yaml /var/lib/docker/volumes/gnosis_config/_data/
-                ;;
-            "matic")
-                if [ "$(docker volume ls -f name=matic_config | awk '{print $NF}' | grep -E '^'matic_config'$')" ]; then
-                    rm -rf /var/lib/docker/volumes/matic_config/_data/config.yaml
-                else
-                    docker volume create matic_config
-                fi
-                cp $NODE_DIR/matic/config.yaml /var/lib/docker/volumes/matic_config/_data/
-                ;;
             "arbitrum-one")
-                ;;
-            "avalanche")
-                if [ "$(docker volume ls -f name=avalanche_config | awk '{print $NF}' | grep -E '^'avalanche_config'$')" ]; then
-                    rm -rf /var/lib/docker/volumes/avalanche_config/_data/config.json
-                else
-                    docker volume create avalanche_config
-                fi
-                cp $NODE_DIR/avalanche/node.json /var/lib/docker/volumes/avalanche_config/_data/
-                if [ "$(docker volume ls -f name=avalanche-c_config | awk '{print $NF}' | grep -E '^'avalanche-c_config'$')" ]; then
-                    rm -rf /var/lib/docker/volumes/avalanche-c_config/_data/config.json
-                else
-                    docker volume create avalanche-c_config
-                fi
-                cp $NODE_DIR/avalanche/config.json /var/lib/docker/volumes/avalanche-c_config/_data/
-                ;;
+                container=$1-nitro
+            ;;
             "optimism")
-                rm -rf /data/optimism/scripts/*
-                cp $NODE_DIR/optimism/scripts/* /data/optimism/scripts/
-                ;;
+                container=$1-op-geth
+            ;;
             *)
-                echo "Chain not supported yet!"
-                return
-                ;;
+                container=$1
+            ;;
         esac
-
-        COMPOSE_PROJECT_NAME=$1 COMPOSE_FILE=$NODE_DIR/$1/$1.yml docker compose --env-file $NODE_DIR/$1/$1.env pull
-        COMPOSE_PROJECT_NAME=$1 COMPOSE_FILE=$NODE_DIR/$1/$1.yml docker compose --env-file $NODE_DIR/$1/$1.env up -d --remove-orphans --build
-
-        if [ ! -z "$HOST" ]; then
-            case $1 in
-                "arbitrum-one")
-                    container=$1-nitro
-                ;;
-                "optimism")
-                    container=$1-op-geth
-                ;;
-                *)
-                    container=$1
-                ;;
-            esac
-            nets=$(docker container inspect --format '{{range $net,$v := .NetworkSettings.Networks}}{{printf "%s\n" $net}}{{end}}' $container)
-            if [[ ! ${nets[@]} =~ "reverse-proxy" ]]; then
-                docker network connect reverse-proxy $container
-            fi
-
-            VHOST_PATH=/var/lib/docker/volumes/reverse-proxy_vhost/_data
-            [ -f "${VHOST_PATH}/${SUBDOMAIN:-$1}.${HOST}" ] && rm ${VHOST_PATH}/${SUBDOMAIN:-$1}.${HOST}
-
-            if [ ! -z $WHITELIST ]; then
-                for (( j=0; j<${#WHITELIST[@]}; j++ )); do
-                    echo "allow ${WHITELIST[$j]};" >> ${VHOST_PATH}/${SUBDOMAIN:-$1}.${HOST}
-                done
-                echo "deny all;" >> ${VHOST_PATH}/${SUBDOMAIN:-$1}.${HOST}
-            fi
+        nets=$(docker container inspect --format '{{range $net,$v := .NetworkSettings.Networks}}{{printf "%s\n" $net}}{{end}}' $container)
+        if [[ ! ${nets[@]} =~ "reverse-proxy" ]]; then
+            docker network connect reverse-proxy $container
         fi
-    else
-        echo "$1 configuration file not found."
+
+        VHOST_PATH=/var/lib/docker/volumes/reverse-proxy_vhost/_data
+        [ -f "${VHOST_PATH}/${SUBDOMAIN:-$1}.${HOST}" ] && rm ${VHOST_PATH}/${SUBDOMAIN:-$1}.${HOST}
+
+        if [ ! -z $WHITELIST ]; then
+            for (( j=0; j<${#WHITELIST[@]}; j++ )); do
+                echo "allow ${WHITELIST[$j]};" >> ${VHOST_PATH}/${SUBDOMAIN:-$1}.${HOST}
+            done
+            echo "deny all;" >> ${VHOST_PATH}/${SUBDOMAIN:-$1}.${HOST}
+        fi
     fi
 }
 
 node-stop() {
-    if [ -f "$NODE_DIR/$1/$1.yml" ]; then
-        COMPOSE_PROJECT_NAME=$1 COMPOSE_FILE=$NODE_DIR/$1/$1.yml docker compose --env-file $NODE_DIR/$1/$1.env stop
-    else
-        echo "$1 configuration file not found."
-    fi
+    [ -f "$NODE_DIR/$1/$1.yml" ] || { echo "Error: $1.yml file not found."; return 1; }
+    [ -f "$NODE_DIR/$1/$1.env" ] || { echo "Error: $1.env file not found"; return 1; }
+
+    COMPOSE_PROJECT_NAME=$1 \
+    COMPOSE_FILE=$NODE_DIR/$1/$1.yml \
+    docker compose --env-file $NODE_DIR/$1/$1.env stop
 }
 
 node-restart() {
